# Generated by Django 4.0.6 on 2022-08-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team3pj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('content', models.TextField()),
                ('name', models.TextField(max_length=128)),
                ('date', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField()),
            ],
        ),
    ]
