# Generated by Django 4.0.6 on 2022-07-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysb', '0001_initial_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='rdate',
            field=models.DateTimeField(),
        ),
    ]
