# Generated by Django 4.0.6 on 2022-07-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysb', '0002_alter_address_rdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('pwd', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('rdate', models.DateTimeField()),
                ('udate', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='brd',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='brd',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brd',
            name='subject',
            field=models.TextField(),
        ),
    ]
